[package]
name = "shazam"
version = "0.1.0"
edition = "2024"
license = "MIT"

[[bin]]
name = "shazam-server"
path = "src/bin/server.rs"

[profile.dev]
opt-level = 0
debug = 2
incremental = true
overflow-checks = true
panic = "unwind"

[profile.release]
opt-level = 3
debug = 1
lto = "thin"
codegen-units = 1
incremental = false
overflow-checks = false
panic = "abort"

[profile.bench]
opt-level = 3
debug = 1
lto = "thin"
codegen-units = 1
incremental = false
overflow-checks = false


[dependencies]
actix-files = "0.6"
actix-multipart = "0.7"
actix-web = "4"
dotenvy = "0.15"
futures-util = "0.3"
hound = "3.5"
rubato = "0.14"
rustfft = "6"
mime = "0.3"
reqwest = { version = "0.12", default-features = false, features = ["json", "rustls-tls"] }
serde = { version = "1", features = ["derive"] }
log = "0.4"
env_logger = "0.11"
rayon = "1.11"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "fs", "io-util", "process", "time"] }
uuid = { version = "1", features = ["v4"] }
tokio-postgres = "0.7.16"
deadpool-postgres = "0.14.1"
bytes = "1.11.0"

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "fingerprinting"
harness = false

[[bench]]
name = "fingerprint_workload"
harness = false
